name: yaml_fluency
description: >
  Write YAML using a fluent syntax. Supports the core types you'd expect, and
  can be extended easily.
repository: https://github.com/madewithfelt/yaml_fluency
version: 2.0.1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  pedantic: ^1.8.0
  meta: ^1.0.0

dev_dependencies:
  test: ^1.6.0
  yaml: ^3.1.0
