name: yaml_fluency
description: Writes YAML strings fluently
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  pedantic: ^1.8.0
  meta: ^1.0.0

dev_dependencies:
  test: ^1.6.0
  yaml: ^2.2.0
